package main

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
)

func CommandMap() error {
	res, err := http.Get("https://pokeapi.co/api/v2/location-area/")
	if err != nil {
		log.Fatal(err)
	}
	body, err := io.ReadAll(res.Body)
	res.Body.Close()
	if res.StatusCode > 299 {
		log.Fatalf("Response failed with status code: %d and\nbody: %s\n", res.StatusCode, body)
	}
	if err != nil {
		log.Fatal(err)
	}
	// fmt.Printf("%s", body)

	type AutoGenerated struct {
		Count    int `json:"count"`
		Next     any `json:"next"`
		Previous any `json:"previous"`
		Results  []struct {
			Name string `json:"name"`
			URL  string `json:"url"`
		} `json:"results"`
	}

	dat := []byte(body)
	user := AutoGenerated{}
	errk := json.Unmarshal(dat, &user)
	if errk != nil {
		fmt.Println(errk)
	}
	results := user.Results
	for num, result := range results {
		if num < 20 {
			fmt.Println(result.Name)
		}
	}
	return nil
}
